name: Node.js CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [main]

jobs:
  # This job will run linting, typechecking and tests on your codebase
  testCodebase:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.14.2
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
      # Install packages
      - run: npm ci

      # Generate prisma client & push to db
      #- run: echo "DATABASE_URL=$DATABASE_URL" > .env
      #- run: cat .env
      - run: npx prisma db push
      - run: npx prisma generate
      # Run linting and typechecking
      - run: npm run lint
      - run: npm run typecheck
      # Run tests
      - run: npm run test

      # start app in dev mode and load `/`-index page
      - run: "(timeout 60 npm run dev & (sleep 10 && curl --fail localhost:3000)) && echo Run development check successful"

      # build & start app in production mode and load `/`-index page
      - run: "npm run build && (timeout 60 npm run preview & (sleep 10 && curl --fail localhost:3000)) && echo Run production check successful"
