
name: CI

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ main ]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.14.2
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2

      - name: Setup
        run: npm i -g @antfu/ni

      - name: Install
        run: nci

      - name: Push Prisma schema
        run: nr prisma db push

      - name: Generate Prisma types
        run: nr prisma generate

      - name: Lint
        run: nr lint

      - name: Typecheck
        run: nr typecheck

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.14.2
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2

      - name: Setup
        run: npm i -g @antfu/ni

      - name: Install
        run: nci

      - name: Build
        run: nr build
